[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Build processing settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Context-specific builds
[context.production]
  command = "npm run validate:env && npm run build"
  [context.production.environment]
    NODE_ENV = "production"
    VITE_BUILD_MODE = "production"
    VITE_APP_ENVIRONMENT = "production"

[context.deploy-preview]
  command = "npm run validate:env && npm run build:dev"
  [context.deploy-preview.environment]
    NODE_ENV = "development"
    VITE_BUILD_MODE = "preview"
    VITE_APP_ENVIRONMENT = "staging"

[context.branch-deploy]
  command = "npm run validate:env && npm run build:dev"
  [context.branch-deploy.environment]
    NODE_ENV = "development"
    VITE_BUILD_MODE = "branch"
    VITE_APP_ENVIRONMENT = "development"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy for Supabase Edge Functions (if needed)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.openai.com https://api.anthropic.com; frame-ancestors 'none';"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Static asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Service worker caching
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Manifest caching
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Performance optimizations
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Edge Functions configuration (if using Netlify Edge Functions)
[[edge_functions]]
  function = "health-check"
  path = "/api/health"

# Environment-specific configurations
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
