// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbaqyzdixamkrssfpxdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiYXF5emRpeGFta3Jzc2ZweGR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzEzODksImV4cCI6MjA2NTcwNzM4OX0.js2PgzN7oinksJE8t2xH6-AuBnwBWcP8aWs4VFHMr0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);